### ISSUE TITLE
Required Knowledge and Skills - categories

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#28]
Under [Required Knowledge and Skills](https://github.com/StoneyJackson/github-workflow-activity/tree/rewrite2#required-knowledge-and-skills) I view cd as a file system operation. I'm thinking that the git commands would be command line operations. Thoughts?

**Comment by StoneyJackson** [comment]
Address this in #27

**Comment by StoneyJackson** [comment]
The command-line operations are commands that you must be able to perform at the command-line. Changing directory is important to for positioning the current working directory of the shell and cannot be performed any other way (that I know of).

Although the operations under file system can be performed using the command-line, do not have to be performed from the command-line to make this activity work. One could use a GUI file-browser.

Is there a better way to express this?


Git is not a prerequisite, we will be teaching it from a command

**Comment by burdged** [comment]
Okay, this makes sense. I didn't think about it that way.
