### ISSUE TITLE
Learning Outcomes

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#29]
In [Learning Outcomes](https://github.com/StoneyJackson/github-workflow-activity/tree/rewrite2#learning-outcomes) you have:
Create a remote in local repository to a remote repository

I understand what you mean, but the wording is confusing to me. My understanding is that you are connecting to a remote. What about "Connect local repository to remote repository"?

**Comment by StoneyJackson** [comment]
Address this in #27
