### ISSUE TITLE
activity.md - form teams

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#31]
[form-teams](https://github.com/StoneyJackson/github-workflow-activity/blob/rewrite2/activity.md#form-teams)
A couple of things here:
1) The formation of teams was already a bullet item in the README -- maybe pull that bulleted item from the README -- it makes more sense for the formation of teams to be here
2) Given:
There are two roles: maintainer and contributor. Each team member play each role at different times while playing out different scenarios. Rotate roles before each scenario, and consider replaying a scenario with team members playing different roles.
What about:
There are two roles: maintainer and contributor. Each team member will adopt each role at different times while playing out different scenarios. Rotate roles before each scenario, and consider replaying a scenario with team members taking on different roles.

**Comment by StoneyJackson** [comment]
(I'm linking these to the PR I'm working on for easier access.)
Address this in #27

**Comment by burdged** [comment]
Not sure that I understand. Do you want me to do something differently?

**Comment by StoneyJackson** [comment]
Nope. Just marking them for myself. (Not sure what I'm doing really. But trying to be organized.)

**Comment by StoneyJackson** [comment]
Ok, I just realized that I can mark the commit with the issue number, and the issue will then be linked to the commit. That way I'll know which I have done and which I haven't.
