### ISSUE TITLE
1st Contribution

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#34]
[1st Contribution](https://github.com/StoneyJackson/github-workflow-activity/blob/rewrite2/activity.md#scenario-1-first-contribution)

You have:
1. Assign maintainer to one team member
2. Assign contributor to another team member.
Suggested change:
1. Assign _the role of_ maintainer to one team member. [missing period]
2. Assign _the role of_ contributor to another team member.

Also, I'm concerned that the "Claim an issue" step (under Prepare to work on an issue) is going to be confusing for POSSE participants. There will be no issue for them to claim. I'm not sure how/where to note this. I think it may be best to put this note in the bullet below #3 that tells them to create favorite-foods.txt. Maybe we can talk about this.

The _Push changes in feature branch to your fork_ link (under _Work on an issue_) does not do/go anywhere.

In 4 there is a link to _Review a pull-request_, but this results in a 404.

**Comment by StoneyJackson** [comment]
In contributor.md I integrated "Alternatively if you have an idea but don't see an issue for it, create an issue" into the 4th bullet of claiming an issue.

This step is very artificial for such small changes. However, there are two good reasons for it. First, there are many projects out there that want you to start a discussion about a proposed change before you start working on it. Second, checking the issue tracker before making a change is a good habit to get into.

Although, there are projects that allow pull-requests only (i.e., no accompanying issue(s)). It's a viable workflow, and we could endorse it. But folks should still check the issue tracker before working on something, and if there is an issue there that matches what they plan to do, they should claim it first. I feel like I just talked myself into leaving it again :)
