### ISSUE TITLE
Contribution Workflow - Claim an issue

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#48]
[Contribution workflow](https://github.com/StoneyJackson/github-workflow-activity/blob/doc-per-task/activity/contribution-workflow.md#contribution-workflow)
Okay, I'm doing this for the first time as a contributor...when a participant gets to this page I think that they will be confused about what they should/should not do. Maybe clarify by including the additional text below to the title:

Claim an issue (applicable only if you are planning to work on an existing issue)

**Comment by StoneyJackson** [comment]
The instructions account for the case when there aren't any issues.
"4. If no reasonable issue exists for what you want to do, create one."
Would it help if the title were something like "Find or create and claim an issue"?

**Comment by burdged** [comment]
Yes, I think that would help. I’m also thinking that we might want to be explicit about this when face-to-face.

Darci L. Burdge
Assistant Chair and Professor of Computer Science
MAT/CSC/ITE Department
Nassau Community College
(516)572-7383 ext. 26826
