### ISSUE TITLE
PR - Creating and Comparing Across Forks

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#54]
[Creating a pull request](https://github.com/StoneyJackson/github-workflow-activity/blob/doc-per-task/activity/contribution-workflow.md#create-a-feature-branch-and-a-pull-request-pr-for-your-work)

There are now two options, but when I click the grayed "Create a pull request" I still need to click "compare across forks" to make sure that all the settings listed are correct.

**Comment by StoneyJackson** [comment]
Hmm... maybe I have to cover both paths.
```
* click grey "Create a pull request" button and then click "compare across forks" links
or
* click green "Compare & pull request" button (if it exists)
...
```
