### ISSUE TITLE
In activity.md - Contributor 2 setup...

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/github-workflow-activity#9]
https://github.com/StoneyJackson/github-workflow-activity/blob/master/activity.md#contributor-2-setup-and-second-contribution

In the last bullet, you have:
Make sure that the maintainer has accepted contributor-2's pull-request and contributor-2 has cleaned up.

Should this say "Make sure that the maintainer has accepted contributor-2's pull-request and contributor-2 has updated their master and cleaned up."?

**Comment by StoneyJackson** [comment]
Yup again. Fixed.

And thanks for the link. That was VERY handy.
